### ISSUE TITLE
How was it trained?

### ISSUE THREAD

**Issue by MircoBerlin** [gmoican/PunkMuff#7]
@gmoican thank you for the project!

Do you let us know how the json was trained? Is it from the GuitarML repo?

Thank you!

**Comment by gmoican** [comment]
Yes indeed. I used the GuitarML repo in Google Collab for the training. I followed a process almost identical to Keith's knob capture demostration, only minor tweaks to adjust the parametrization.

Thank you for your feedback!

**Comment by MircoBerlin** [comment]
@gmoican thank you! :)
